###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    php-fpm:
      build: phpdocker/php-fpm
      container_name: burak-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
        
    mysql:
      image: mysql:5.7
      container_name: burak-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=111111
        - MYSQL_DATABASE=burak
        - MYSQL_USER=burak
        - MYSQL_PASSWORD=123456
      ports:
        - "3000:3306"

    webserver:
      image: nginx:alpine
      container_name: burak-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"
      tty: true 

